//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowEvents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Task_ID_PK { get; set; }
        public string TaskName { get; set; }
        public string TaskDesc { get; set; }
        public int CreatedBY { get; set; }
        public System.DateTime CreatedDated { get; set; }
        public Nullable<int> ModifedBy { get; set; }
        public Nullable<System.DateTime> ModifedDate { get; set; }
        public int StatusID_FK { get; set; }
    }
}
