//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowEvents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public int UserRole_ID_PK { get; set; }
        public string UserRole_Name { get; set; }
    }
}
